# Generated by Django 3.2.15 on 2022-09-16 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20220916_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersub',
            name='sub_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usersub',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
