# Generated by Django 3.2.15 on 2022-09-16 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_alter_usersub_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersub',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
