# Generated by Django 3.2.15 on 2022-09-16 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_auto_20220916_0852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersub',
            old_name='sub_id',
            new_name='sub',
        ),
        migrations.RenameField(
            model_name='usersub',
            old_name='user_id',
            new_name='user',
        ),
    ]
