# Generated by Django 3.2.15 on 2022-09-16 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0011_auto_20220916_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersub',
            name='sub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_sub', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usersub',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sub', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_read', to='article.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_read', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
